(() => {
 const $=id=>document.getElementById(id),M=window.MapCore,I=window.InstagramCore,config=JSON.parse($('map-config').textContent),pool=JSON.parse($('wallpaper-pool').textContent),prefix=document.body.dataset.prefix,calendarImages=JSON.parse($('map-image-assets').textContent);
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let calendar=config.calendarPresent?config.calendar:null,instagram=config.visitor?M.scheduledSelection(config.schedule):config.instagram,releaseTimer=null,layer='calendar',map=null,markers=null,tileErrors=0;
 try{if(!config.visitor&&document.body.dataset.mode!=='local'){const cal=localStorage.getItem('toskana-2027-selection-v1'),ig=localStorage.getItem('toskana-2027-instagram-v1');calendar=cal===null?null:JSON.parse(cal);instagram=ig===null?config.instagram:I.validateSelection(JSON.parse(ig),pool);}if(calendar)I.calendarSources(calendar,pool,config.policy);}
 catch(e){$('map-status').textContent='Die gespeicherte Auswahl kann nicht gelesen werden. Bitte in der Monatsrunde prüfen. Die Karte zeigt vorläufig den öffentlichen Entwurf.';calendar=null;instagram={items:{}};}
 $('map-selection-note').textContent=config.visitor?'Die dreizehn Kalendermotive sind immer dabei. Die Instagram-Ebene ergänzt Bilder nach unserem Postingplan – jeweils ab dem vorgesehenen Termin (deutsche Zeit).':calendar===null?'Kalenderentwurf: die bereits auf der Rückseite gezeigten Motive. Sobald du eigene Monate wählst, zeigt die Karte deine Auswahl. Instagram ergänzt die in diesem Browser bzw. Projekt gewählten Bilder.':'Deine gespeicherte Auswahl einschließlich der Titelseite. Die zweite Ebene ergänzt deine gewählten Instagram-Bilder.';
 try{if(!window.L)throw Error();map=L.map('travel-map',{scrollWheelZoom:false}).setView([43.43,10.87],8);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).on('tileerror',()=>{if(++tileErrors>=3)$('map-status').textContent='Die Kartenkacheln sind gerade nicht erreichbar. Alle Bilder und Ortslinks bleiben unten verfügbar.';}).addTo(map);markers=L.featureGroup().addTo(map);}
 catch(e){$('travel-map').textContent='Die Karte ist gerade nicht verfügbar. Nutze die Bildliste und die Ortslinks unten.';$('map-fit').disabled=true;}
 function locationLabel(i){const p=config.locations[i.source_id];return M.valid(p)?(p.precision==='gps'?'Foto-GPS':'Ort ungefähr'):'Ort noch offen';}
 function google(i){const p=config.locations[i.source_id];return M.valid(p)?'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.lat+','+p.lon):'';}
 function fit(){if(map&&markers.getLayers().length)map.fitBounds(markers.getBounds().pad(.18),{maxZoom:12});}
 function render(fitView=true){
  const rows=M.entries(layer,pool,calendar,instagram,config.policy,config.draft),groups=M.groups(rows,config.locations);document.querySelectorAll('[data-layer]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.layer===layer)));
  $('map-count').textContent=rows.length+' Bilder · '+new Set(rows.map(i=>i.place_slug)).size+' Orte';
  $('map-list').innerHTML=rows.map(i=>`<article class="map-card"><a href="${prefix}${i.kind==='painting'?'bilder/'+encodeURIComponent(i.id)+'/':'instagram/?foto='+encodeURIComponent(i.source_id)+'&ort='+encodeURIComponent(i.place_slug)}"><img src="${prefix}assets/${M.imageAsset(i,calendarImages)}" alt="${esc(i.title)}" loading="lazy" width="1600" height="900"></a><div><p class="eyebrow">${esc(i.uses.join(' · '))}</p><h3>${esc(i.place)}</h3><p>${esc(i.artist||'Originalfoto')}${i.palette?' · '+esc(i.palette):''}</p><p class="small">${locationLabel(i)}</p><div class="map-card-links">${M.valid(config.locations[i.source_id])?`<button type="button" data-locate="${esc(i.id)}">Auf Karte zeigen</button><a href="${google(i)}" target="_blank" rel="noopener">Google Maps ↗</a>`:''}</div>${config.visitor?`<a class="text-link" href="${prefix}maler-orte/#${esc(i.place_slug)}">Ort &amp; Maler kennenlernen →</a>`:`<label class="wallpaper-choice"><input type="checkbox" data-wallpaper-id="${esc(i.id)}"> Für Hintergrund &amp; Bildschirmschoner</label>`}</div></article>`).join('');
  if(config.visitor&&layer==='all')$('map-count').textContent+=' · '+Object.keys(instagram.items).length+' Instagram-'+(Object.keys(instagram.items).length===1?'Motiv':'Motive')+' nach Plan freigeschaltet';
  if(!rows.length)$('map-count').textContent='Noch keine Bilder für diese Ansicht gewählt.';
  if(map){markers.clearLayers();for(const g of groups){const igOnly=g.items.every(i=>i.uses.length===1&&i.uses[0]==='Instagram'),icon=L.divIcon({className:'picture-pin '+(igOnly?'pin-instagram':g.items.some(i=>i.uses.includes('Instagram'))?'pin-mixed':'pin-calendar'),html:`<img src="${prefix}assets/${M.imageAsset(g.items[0],calendarImages)}" alt=""><span>${g.items.length}</span>`,iconSize:[54,33],iconAnchor:[27,40],popupAnchor:[0,-36]});const marker=L.marker([g.lat,g.lon],{icon,title:g.items[0].place+' · '+g.items.length+' Bilder',alt:g.items[0].place}).addTo(markers);marker.getElement().setAttribute('aria-label',g.items[0].place+' · '+g.items.length+' Bilder öffnen');marker.bindPopup(`<div class="map-popup">${g.items.map(i=>`<a href="${prefix}${i.kind==='painting'?'bilder/'+encodeURIComponent(i.id)+'/':'instagram/?foto='+encodeURIComponent(i.source_id)+'&ort='+encodeURIComponent(i.place_slug)}"><img src="${prefix}assets/${M.imageAsset(i,calendarImages)}" alt="${esc(i.title)}" width="1600" height="900"><strong>${esc(i.place)} · ${esc(i.artist||'Originalfoto')}</strong></a><p>${esc(i.uses.join(' · '))} · ${locationLabel(i)}</p>`).join('')}</div>`,{maxWidth:280,maxHeight:350});marker.sourceIds=new Set(g.items.map(i=>i.id));}if(fitView)fit();}
 }
 function refreshSchedule(){
  if(!config.visitor)return;
  const next=M.scheduledSelection(config.schedule);
  if(JSON.stringify(next)!==JSON.stringify(instagram)){instagram=next;render(false);}
  clearTimeout(releaseTimer);
  const release=M.nextRelease(config.schedule);
  if(release!==null)releaseTimer=setTimeout(refreshSchedule,Math.min(2147483647,Math.max(50,release-Date.now()+50)));
 }
 window.addEventListener('focus',refreshSchedule);
 window.addEventListener('pageshow',refreshSchedule);
 document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refreshSchedule();});
 document.querySelectorAll('[data-layer]').forEach(b=>b.addEventListener('click',()=>{layer=b.dataset.layer;render();}));$('map-fit').addEventListener('click',fit);$('map-list').addEventListener('click',e=>{const b=e.target.closest('[data-locate]');if(!b||!map)return;const marker=markers.getLayers().find(m=>m.sourceIds.has(b.dataset.locate));if(marker){map.setView(marker.getLatLng(),14);marker.openPopup();$('travel-map').scrollIntoView({behavior:'smooth',block:'center'});}});window.addEventListener('storage',e=>{if(!config.visitor&&(e.key===null||['toskana-2027-selection-v1','toskana-2027-instagram-v1'].includes(e.key)))$('map-status').textContent='Die Bildauswahl wurde in einem anderen Fenster geändert. Bitte die Seite neu laden.';});render();refreshSchedule();
})();
